### ISSUE TITLE
Mac Version Crashes upon execution

### ISSUE THREAD

**Issue by ikesicle** [vishnupsatish/hand-cricket#2]
Upon execution of the Mac Version of Hand Cricket, the user is immediately signed out and no crash logs are provided.

Version is MacOS Version 10.16 Mojave on a 2017 Macbook Pro.

**Comment by vishnupsatish** [comment]
I cannot reproduce the issue since running it from the app works too. Must be an error with the application creation process or the Py2App program since running the files without creating an application works as expected. Sorry for the issue.

**Comment by vishnupsatish** [comment]
Hello. This is a completely different Hand Cricket you are referring to. This is the Android version. The other Mac and Windows app is currently not on GitHub. Thanks for understanding.
